name: CI/CD Integration 💥

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        

      - name: Pull latest code into Blood_Production directory
        run: |
          cd /var/www/Blood_Production  
          git fetch origin main    
          git reset --hard origin/main 
          
      - name: Fix Storage Permissions
        run: |
          sudo chmod -R 775 /var/www/Blood_Production/storage
          sudo chmod -R 775 /var/www/Blood_Production/bootstrap/cache