name: CI/CD Integration

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code into Blood_Production directory
        run: |
          cd /var/www/Blood_Production
          git config --global --add safe.directory /var/www/Blood_Production
          git fetch origin master
          git reset --hard origin/master

      - name: Install Composer dependencies
        run: |
          cd /var/www/Blood_Production
          composer install --no-dev --optimize-autoloader

      - name: Laravel optimize and migrate
        run: |
          cd /var/www/Blood_Production
          php artisan migrate --force
          php artisan optimize:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache